repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
    args: ["--allow-multiple-documents"]
  - id: check-json
  - id: pretty-format-json
  - id: check-symlinks
  - id: check-docstring-first
  - id: detect-private-key
  - id: no-commit-to-branch
    args: ["--branch", "main", "--branch", "master"]
  - id: check-merge-conflict
  - id: check-added-large-files
  - id: check-shebang-scripts-are-executable
- repo: https://github.com/gitleaks/gitleaks
  rev: v8.28.0
  hooks:
    - id: gitleaks
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.99.5
  hooks:
    - id: terraform_fmt
    # refer point 4 in https://github.com/antonbabenko/pre-commit-terraform?tab=readme-ov-file#terraform_validate to understand exclude pattern
    - id: terraform_validate
      exclude: '^[^/]+$'
    - id: terraform_tflint
      exclude: examples/
      args:
        - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl --fix
- repo: https://github.com/bridgecrewio/checkov.git
  rev: "3.2.452"
  hooks:
    - id: checkov
      args: ["--quiet", "--compact", "--framework", "terraform", "--download-external-modules", "false", "--skip-path", "examples"]
- repo: https://github.com/terraform-docs/terraform-docs
  rev: v0.20.0
  hooks:
    - id: terraform-docs-go
      args: ["."]
